import type { Metadata } from "next";
import { Stack_Sans_Headline, Manrope } from "next/font/google";
import "./globals.css";

const settingsFont = Manrope({
  variable: "--font-setting",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Asistente Legal AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${settingsFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
